/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describe the parameters available for the Arduino CLI configuration file. This schema should be considered unstable at this moment, it is not used by the CLI to validate input configuration
 */
export interface ArduinoCLIConfigurationSchema {
    board_manager?: {
        /**
         * the URLs to any additional Boards Manager package index files needed for your boards platforms.
         */
        additional_urls?: string[];
        /**
         * set to `true` to allow installation of packages that do not pass the checksum test. This is considered an unsafe installation method and should be used only for development purposes.
         */
        enable_unsafe_install?: boolean;
    };
    /**
     * configuration options related to the compilation cache
     */
    build_cache?: {
        /**
         * the path to the build cache, default is `$TMP/arduino`.
         */
        path?: string;
        /**
         * a list of paths to look for precompiled artifacts if not found on `build_cache.path` setting.
         */
        extra_paths?: string[];
        /**
         * interval, in number of compilations, at which the cache is purged, defaults to `10`. When `0` the cache is never purged.
         */
        compilations_before_purge?: number;
        /**
         * cache expiration time of build folders. If the cache is hit by a compilation the corresponding build files lifetime is renewed. The value format must be a valid input for time.ParseDuration(), defaults to `720h` (30 days)
         */
        ttl?: string;
    };
    /**
     * options related to running Arduino CLI as a [gRPC] server.
     */
    daemon?: {
        /**
         * TCP port used for gRPC client connections.
         */
        port?: string;
    };
    /**
     * directories used by Arduino CLI.
     */
    directories?: {
        builtin?: {
            /**
             * the libraries in this directory will be available to all platforms without the need for the user to install them, but with the lowest priority over other installed libraries with the same name, it's the equivalent of the Arduino IDE's bundled libraries directory.
             */
            libraries?: string;
            /**
             * it's a list of directories of tools that will be available to all platforms without the need for the user to install them, it's the equivalent of the Arduino IDE 1.x bundled tools directory.
             */
            tools?: string[];
        };
        /**
         * directory used to store Boards/Library Manager index files and Boards Manager platform installations.
         */
        data?: string;
        /**
         * directory used to stage downloaded archives during Boards/Library Manager installations.
         */
        downloads?: string;
        /**
         * the equivalent of the Arduino IDE's ["sketchbook" directory][sketchbook directory]. Library Manager installations are made to the `libraries` subdirectory of the user directory.
         */
        user?: string;
    };
    /**
     * configuration options relating to Arduino libraries.
     */
    library?: {
        /**
         * set to `true` to enable the use of the `--git-url` and `--zip-file` flags with [`arduino-cli lib install`][arduino cli lib install]. These are considered "unsafe" installation methods because they allow installing files that have not passed through the Library Manager submission process.
         */
        enable_unsafe_install?: boolean;
    };
    /**
     * the language used by Arduino CLI to communicate to the user, the parameter is the language identifier in the standard POSIX format `<language>[_<TERRITORY>[.<encoding>]]` (for example `it` or `it_IT`, or `it_IT.UTF-8`).
     */
    locale?: string;
    /**
     * configuration options for Arduino CLI's logs.
     */
    logging?: {
        /**
         * path to the file where logs will be written.
         */
        file?: string;
        /**
         * output format for the logs. Allowed values are `text` or `json`.
         */
        format?: 'text' | 'json';
        /**
         * messages with this level and above will be logged. Valid levels are: `trace`, `debug`, `info`, `warn`, `error`, `fatal`, `panic`.
         */
        level?:
            | 'trace'
            | 'debug'
            | 'info'
            | 'warn'
            | 'error'
            | 'fatal'
            | 'panic';
    };
    /**
     * settings related to the collection of data used for continued improvement of Arduino CLI.
     */
    metrics?: {
        /**
         * TCP port used for metrics communication.
         */
        addr?: string;
        /**
         * controls the use of metrics.
         */
        enabled?: boolean;
    };
    /**
     * settings related to network connections.
     */
    network?: {
        /**
         * proxy settings for network connections.
         */
        proxy?: string;
        /**
         * extra string to append to the user agent string in HTTP requests.
         */
        user_agent_ext?: string;
        /**
         * timeout for network connections, defaults to '30s'
         */
        connection_timeout?: string;
        /**
         * settings related to the Arduino Cloud API.
         */
        cloud_api?: {
            /**
             * do not call the Arduino Cloud API to detect an unknown board
             */
            skip_board_detection_calls?: boolean;
        };
    };
    /**
     * settings related to text output.
     */
    output?: {
        /**
         * ANSI color escape codes are added by default to the output. Set to `true` to disable colored text output.
         */
        no_color?: boolean;
    };
    /**
     * configuration options relating to [Arduino sketches][sketch specification].
     */
    sketch?: {
        /**
         * set to `true` to make [`arduino-cli compile`][arduino-cli compile] always save binaries to the sketch folder. This is the equivalent of using the [`--export-binaries`][arduino-cli compile options] flag.
         */
        always_export_binaries?: boolean;
    };
    /**
     * configuration options related to Arduino CLI updates
     */
    updater?: {
        /**
         * set to `false` to disable notifications of new Arduino CLI releases, defaults to `true`
         */
        enable_notification?: boolean;
    };
}
