export {
    type BoardDetailsRequest,
    type BoardDetailsResponse,
    type BoardIdentificationProperties,
    type BoardIdentificationProperties_PropertiesEntry,
    type Package,
    type Help,
    type BoardPlatform,
    type ToolsDependencies,
    type Systems,
    type ConfigOption,
    type ConfigValue,
    type BoardAttachRequest,
    type BoardAttachResponse,
    type BoardListRequest,
    type BoardListResponse,
    type DetectedPort,
    type BoardListAllRequest,
    type BoardListAllResponse,
    type BoardListWatchRequest,
    type BoardListWatchResponse,
    type BoardListItem,
    type BoardSearchRequest,
    type BoardSearchResponse,
} from './cc/arduino/cli/commands/v1/board';
export {
    type CreateRequest,
    type CreateResponse,
    type InitRequest,
    type InitResponse,
    type InitResponse_Progress,
    type DestroyRequest,
    type DestroyResponse,
    type UpdateIndexRequest,
    type UpdateIndexResponse,
    type UpdateLibrariesIndexRequest,
    type UpdateLibrariesIndexResponse,
    type UpdateCoreLibrariesIndexRequest,
    type UpdateCoreLibrariesIndexResponse,
    type OutdatedRequest,
    type OutdatedResponse,
    type UpgradeRequest,
    type UpgradeResponse,
    type VersionRequest,
    type VersionResponse,
    type NewSketchRequest,
    type NewSketchResponse,
    type LoadSketchRequest,
    type LoadSketchResponse,
    type ArchiveSketchRequest,
    type ArchiveSketchResponse,
    type ArduinoCoreServiceDefinition,
    type ArduinoCoreServiceServiceImplementation,
    type ArduinoCoreServiceClient,
} from './cc/arduino/cli/commands/v1/commands';
export {
    type Instance,
    type DownloadProgress,
    type DownloadProgressStart,
    type DownloadProgressUpdate,
    type DownloadProgressEnd,
    type TaskProgress,
    type Programmer,
    type Platform,
    type InstalledPlatformReference,
    type Board,
    type Profile,
} from './cc/arduino/cli/commands/v1/common';
export {
    type CompileRequest,
    type CompileRequest_SourceOverrideEntry,
    type CompileResponse,
    type ExecutableSectionSize,
} from './cc/arduino/cli/commands/v1/compile';
export {
    type PlatformInstallRequest,
    type PlatformInstallResponse,
    type PlatformDownloadRequest,
    type PlatformDownloadResponse,
    type PlatformUninstallRequest,
    type PlatformUninstallResponse,
    type AlreadyAtLatestVersionError,
    type PlatformUpgradeRequest,
    type PlatformUpgradeResponse,
    type PlatformSearchRequest,
    type PlatformSearchResponse,
    type PlatformListRequest,
    type PlatformListResponse,
} from './cc/arduino/cli/commands/v1/core';
export {
    libraryInstallLocationFromJSON,
    libraryInstallLocationToJSON,
    librarySearchStatusFromJSON,
    librarySearchStatusToJSON,
    libraryLayoutFromJSON,
    libraryLayoutToJSON,
    libraryLocationFromJSON,
    libraryLocationToJSON,
    LibraryInstallLocation,
    LibrarySearchStatus,
    LibraryLayout,
    LibraryLocation,
    type LibraryDownloadRequest,
    type LibraryDownloadResponse,
    type LibraryInstallRequest,
    type LibraryInstallResponse,
    type LibraryUpgradeRequest,
    type LibraryUpgradeResponse,
    type LibraryUninstallRequest,
    type LibraryUninstallResponse,
    type LibraryUpgradeAllRequest,
    type LibraryUpgradeAllResponse,
    type LibraryResolveDependenciesRequest,
    type LibraryResolveDependenciesResponse,
    type LibraryDependencyStatus,
    type LibrarySearchRequest,
    type LibrarySearchResponse,
    type SearchedLibrary,
    type SearchedLibrary_ReleasesEntry,
    type LibraryRelease,
    type LibraryDependency,
    type DownloadResource,
    type LibraryListRequest,
    type LibraryListResponse,
    type InstalledLibrary,
    type Library,
    type Library_PropertiesEntry,
    type Library_CompatibleWithEntry,
    type ZipLibraryInstallRequest,
    type ZipLibraryInstallResponse,
    type GitLibraryInstallRequest,
    type GitLibraryInstallResponse,
} from './cc/arduino/cli/commands/v1/lib';
export {
    type MonitorRequest,
    type MonitorPortConfiguration,
    type MonitorResponse,
    type MonitorPortSetting,
    type EnumerateMonitorPortSettingsRequest,
    type EnumerateMonitorPortSettingsResponse,
    type MonitorPortSettingDescriptor,
} from './cc/arduino/cli/commands/v1/monitor';
export { type Port, type Port_PropertiesEntry } from './cc/arduino/cli/commands/v1/port';
export {
    type UploadRequest,
    type UploadRequest_UserFieldsEntry,
    type UploadResponse,
    type ProgrammerIsRequiredForUploadError,
    type UploadUsingProgrammerRequest,
    type UploadUsingProgrammerRequest_UserFieldsEntry,
    type UploadUsingProgrammerResponse,
    type BurnBootloaderRequest,
    type BurnBootloaderRequest_UserFieldsEntry,
    type BurnBootloaderResponse,
    type ListProgrammersAvailableForUploadRequest,
    type ListProgrammersAvailableForUploadResponse,
    type SupportedUserFieldsRequest,
    type UserField,
    type SupportedUserFieldsResponse,
} from './cc/arduino/cli/commands/v1/upload';
export {
    type DebugRequest,
    type DebugConfigRequest,
    type DebugResponse,
    type GetDebugConfigResponse,
    type GetDebugConfigResponse_ToolchainConfigurationEntry,
    type GetDebugConfigResponse_ServerConfigurationEntry,
    type DebugServiceDefinition,
    type DebugServiceServiceImplementation,
    type DebugServiceClient,
} from './cc/arduino/cli/debug/v1/debug';
export {
    type GetAllResponse,
    type MergeRequest,
    type GetValueResponse,
    type SetValueRequest,
    type GetAllRequest,
    type GetValueRequest,
    type MergeResponse,
    type SetValueResponse,
    type WriteRequest,
    type WriteResponse,
    type SettingsServiceDefinition,
    type SettingsServiceServiceImplementation,
    type SettingsServiceClient,
} from './cc/arduino/cli/settings/v1/settings';
export { type Any } from './google/protobuf/any';
export {
    type DoubleValue,
    type FloatValue,
    type Int64Value,
    type UInt64Value,
    type Int32Value,
    type UInt32Value,
    type BoolValue,
    type StringValue,
    type BytesValue,
} from './google/protobuf/wrappers';
export { type Status } from './google/rpc/status';
